### ISSUE TITLE
Secrets beállítások

### ISSUE THREAD

**Issue by gaborka98** [Teaching-projects/SZE-Projektmunka2-2020-GSP-Art#1]
@hegyhati A repohoz kéne beállítani a ftp eléréshez szükséges dolgokat. Nem tudom ha itt leírom mennyire jó?

**Comment by hegyhati** [comment]
MArmint ilyen secreteket kellene beallitani valahol? Azt le ne ird itt publikusban. Adjak admin jogot?

**Comment by hegyhati** [comment]
Most latom csaka z issue nevet, sorry, akro jol ertettem. megy az admin jog.
